const data = {
  country_name: [
    "India",
    "USA",
    "Japan",
    "China",
    "Germany",
    "France",
    "Canada",
    "Australia",
    "Brazil",
    "Russia",
  ],
  state_name: [
    "Maharashtra",
    "Uttar Pradesh",
    "Bihar",
    "West Bengal",
    "Madhya Pradesh",
    "Tamil Nadu",
    "Rajasthan",
    "Karnataka",
    "Gujarat",
    "Andhra Pradesh",
  ],
  city_name: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Pune",
    "Surat",
    "Jaipur",
  ],
  nationality: [
    "Indian",
    "American",
    "Japanese",
    "Chinese",
    "German",
    "French",
    "Canadian",
    "Australian",
    "Brazilian",
    "Russian",
  ],
};

export default data;
